#!/usr/bin/env python

Import("env")
Import("env_modules")

env_sg_physics_2d = env_modules.Clone()

sg_physics_2d_subdirs = [
    "",
    "math/internal/",
    "math/",
    "scene/2d/",
    "scene/resources/",
    "editor/",
]

for d in sg_physics_2d_subdirs:
    env.add_source_files(env.modules_sources, d + "*.cpp")
